version: "3"

services:
  app:
    build: .
    container_name: app
    # entrypoint: dockerize -template ./.docker/app/.env.template:.env -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    # environment:
    #   - DB_HOST=db
    #   - DB_DATABASE=laravel
    #   - DB_USERNAME=root
    #   - DB_PASSWORD=root
    volumes:
      - ./:/var/www
    depends_on:
      - db
      - redis
    networks:
      - app-network

  ngnix:
    build: .docker/ngnix/.
    container_name: ngnix
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
    depends_on:
      - app
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    expose:
      - 6379
    networks:
      - app-network

  db:
    image: mysql:5.7.22
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - "./.docker/dbdata:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
